# Indexing/Slicing

In [1]:
import numpy as np

In [2]:
m = range(10)
m

range(0, 10)

In [3]:
m[0]   # access the first position of the list

0

In [4]:
m[-1]  # access the last position of the list

9

In [5]:
m[slice(0,5,2)]    # range(start,stop,step)

range(0, 5, 2)

In [6]:
m[::]

range(0, 10)

In [7]:
m[:5]    # first 5 elements of the list

range(0, 5)

In [8]:
m[-5:]   # last 5 elements of the list

range(5, 10)

In [9]:
m[::-1]  # list in reverse order

range(9, -1, -1)

**To enter in pylab mode:**

In [10]:
import numpy as np
import matplotlib.pyplot as plt

**or**:

In [11]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Numpy

**ndarray.ndim,ndarray.shape**

In [12]:
a0 = array(5)  # zero-dimensions
a0

array(5)

In [44]:
a0.ndim  # number of dimensions of the array 

0

In [14]:
a0.shape  # gives the size of each dimension

()

In [48]:
a0.size  # gives the total size of the array

1

In [49]:
a1 = array([1,2])  # 1dim array
a1

array([1, 2])

In [50]:
a1.ndim, a1.shape, a1.size

(1, (2,), 2)

In [51]:
a2 = array(([1,2],[3,4]))  # 2dim array
a2.ndim, a2.shape, a2.size

(2, (2, 2), 4)

In [52]:
a2.shape

(2, 2)

In [53]:
a = arange(10)  # Create an array filled with a linear sequence 
a               # (Starting at 0, ending at 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a.dtype   # Gives the type of the array

dtype('int64')

In [21]:
a = random.random((2,2))  # Create a 2x2 array of random values between 0 and 1
a

array([[0.32785811, 0.09404185],
       [0.89860062, 0.53327055]])

In [22]:
a = random.randint(0,20,(2,2))  # Create a 2x2 array of random integers in the interval [0,20)
a

array([[16,  4],
       [ 4, 15]])

In [23]:
random.seed(0)

In [41]:
x1 = random.randint(10, size=7) # One-dimensional array of Integer numbers
x1

array([2, 3, 2, 0, 8, 8, 3])

In [42]:
x2 = random.randint(10, size=(3,4))  # Two-dimensional array
x2

array([[8, 2, 8, 4],
       [3, 0, 4, 3],
       [6, 9, 8, 0]])

In [43]:
x3 = random.randint(10, size=(3,4,5))  # Three-dimensional array
x3

array([[[8, 5, 9, 0, 9],
        [6, 5, 3, 1, 8],
        [0, 4, 9, 6, 5],
        [7, 8, 8, 9, 2]],

       [[8, 6, 6, 9, 1],
        [6, 8, 8, 3, 2],
        [3, 6, 3, 6, 5],
        [7, 0, 8, 4, 6]],

       [[5, 8, 2, 3, 9],
        [7, 5, 3, 4, 5],
        [3, 3, 7, 9, 9],
        [9, 7, 3, 2, 3]]])

**Array creation routines**

In [25]:
a = array([1,2])
a

array([1, 2])

In [26]:
a = zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [27]:
a = ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [28]:
a = full((2,4),3.14)  # Create a 2x4 array with 3.14
a

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [29]:
a = empty((2,2))  # Create an uninitialized 2x2 array with 1
a

array([[1., 1.],
       [1., 1.]])

In [30]:
a = eye(4)  
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
a = eye(3,4,-1)
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [32]:
a = identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
a = diag(arange(4))
a

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [34]:
a = linspace(1,10,5)  # Create an array of 5 values evenly spaced between 0 and 1
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [35]:
a = logspace(1,2,5)
a

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

**type hierarchy**

In [34]:
a = arange(10, dtype=float)
a.dtype

dtype('float64')

In [35]:
a = arange(10, dtype=byte)
a.dtype

dtype('int8')

In [36]:
a[0] = 128
a[0]

-128

In [37]:
a

array([-128,    1,    2,    3,    4,    5,    6,    7,    8,    9],
      dtype=int8)

In [38]:
a1 = a.astype(int16)
a1[0] = 128
a1[0]

128

In [39]:
a1.dtype

dtype('int16')

**reshape, transpose**

In [40]:
a = arange(64)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

I want to map a 0...63 1d array to a 8x8 2d array

In [41]:
a1 = a.reshape(8,8)
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [42]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [43]:
a.shape  

(64,)

In [44]:
a.shape = (8,8)   # we can decide the shape we want
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [45]:
a.T  # transpose

array([[ 0,  8, 16, 24, 32, 40, 48, 56],
       [ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63]])

**stacking & concatenation**

In [46]:
a = array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [47]:
b = array([[5,6]])
b

array([[5, 6]])

In [48]:
print(a.shape, b.shape)

(2, 2) (1, 2)


In [49]:
x = concatenate((a,b), axis=0) # vertical stack (1st method) 
print(x, x.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [50]:
y = concatenate((a,b.T), axis=1) # vertical stack using concatenate()
print(y, y.shape)

[[1 2 5]
 [3 4 6]] (2, 3)


In [51]:
print(vstack((a,b))) # 2nd method using vstack()
print(hstack((a,b.T)))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [52]:
print(append(a,b,axis=0))   # 3rd method using append()
print(append(a,b.T,axis=1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [53]:
print(insert(a,0,b,axis=0))   # insert b on the top in vertical
print(insert(a,0,b,axis=1))   # insert b on the left 

[[5 6]
 [1 2]
 [3 4]]
[[5 1 2]
 [6 3 4]]


# Numpy Operation

In [54]:
a

array([[1, 2],
       [3, 4]])

In [55]:
2*a

array([[2, 4],
       [6, 8]])

In [56]:
a+2

array([[3, 4],
       [5, 6]])

In [57]:
a = array([range(0,3)]*4)
a

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [58]:
b = array([range(0,40,10)]*3).T
b

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [59]:
a+b   # vector sum

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [60]:
b + arange(0,3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [61]:
arange(0,40,10)  # vector (1,4)

array([ 0, 10, 20, 30])

In [62]:
arange(0,40,10).shape # 1dim vector of 4 elements

(4,)

In [63]:
arange(0,40,10).reshape(4,1) # 1dim vector of 4 rows and 1 column

array([[ 0],
       [10],
       [20],
       [30]])

In [64]:
arange(0,40,10).reshape(4,1).shape  # It has a vectorial structure

(4, 1)

In [65]:
arange(0,3)

array([0, 1, 2])

In [66]:
arange(0,40,10).reshape(4,1) + arange(0,3)  # You need to reshape arange(0,40,10) to give a vectorial structure

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])